# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Server Dependencies
      working-directory: ./server
      run: npm install
      env:
          NODE_ENV: production
          API_URL: ${{ secrets.SERVER_ENV }}
          
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install
      env:
          NODE_ENV: production
          API_URL: ${{ secrets.FRONTEND_ENV }}
          
    - name: Build React App
      working-directory: ./frontend
      run: |
        npm run build
        
    # Debug step to check contents of directories
    - name: Check Server Directory Contents
      working-directory: ./server
      run: ls -la

    - name: Check Frontend Directory Contents
      working-directory: ./frontend
      run: ls -la

        
